/* Main.c file generated by New Project wizard
 *
 * Created:   Tue Apr 15 2025
 * Processor: PIC16F877A
 * Compiler:  MPLAB XC8
 */

#include <xc.h>
// BEGIN CONFIG

void initalization()
{
TRISC = 0x00;//configuring PORTC as output
}
void delay_ms(int ms)
{
int i;
for(i=0;i<ms;i++);
}
int main(int argc, char** argv) {
initalization();
//Loop executed infinite times
while(1)
{
//Pin1 of PORTC high
PORTC=0x02;//0b00000010;
delay_ms(10000); //Delay of 1 sec
//Pin1 of PORTC low
PORTC=0b00000000;
delay_ms(10000);//Delay of 1 sec
}
return 0;
}